# Generated by Django 5.2.17 on 2026-09-05 17:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_minor', models.BooleanField(default=False)),
                ('minor_consent_verified', models.BooleanField(default=False)),
                ('consent_accepted', models.BooleanField(default=False)),
                ('terms_version', models.CharField(blank=True, default='', max_length=50)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('long_term_semantic', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('long_term_acoustic', pgvector.django.vector.VectorField(blank=True, dimensions=128, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('original_file', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('hls_playlist_url', models.CharField(blank=True, max_length=500, null=True)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.CharField(blank=True, max_length=500, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('attribution_text', models.CharField(blank=True, max_length=500, null=True)),
                ('imported_via_scraper', models.BooleanField(default=False)),
                ('original_source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('avg_completion_rate', models.FloatField(default=0.0)),
                ('engagement_velocity', models.FloatField(default=0.0)),
                ('likes', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('skips', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('semantic_vector', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('acoustic_vector', pgvector.django.vector.VectorField(blank=True, dimensions=128, null=True)),
                ('moderation_approved', models.BooleanField(default=False)),
                ('copyright_acknowledgement', models.BooleanField(default=False)),
                ('copyright_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('license_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_clips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('register', 'Register')], max_length=50)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.audioclip')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_issued_at', models.DateTimeField(auto_now_add=True)),
                ('terms_version_id', models.CharField(default='v1.0', max_length=50)),
                ('privacy_version_id', models.CharField(default='v1.0', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consent_issued_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('erasure', 'Erasure')], max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cooling_off_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_subject_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('acknowledged', 'Acknowledged'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='received', max_length=20)),
                ('acknowledgment_due', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.audioclip')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakedownRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requester_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takedown_requests', to='app.audioclip')),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('share', 'Share'), ('skip', 'Skip'), ('view', 'View')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watch_time_ms', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.audioclip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='audioclip',
            index=models.Index(fields=['status', '-created_at'], name='app_audiocl_status_83a349_idx'),
        ),
        migrations.AddIndex(
            model_name='audioclip',
            index=models.Index(fields=['status', '-engagement_velocity'], name='app_audiocl_status_fa835f_idx'),
        ),
        migrations.AddIndex(
            model_name='audioclip',
            index=models.Index(fields=['category', '-likes'], name='app_audiocl_categor_cabc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='audioclip',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['semantic_vector'], m=16, name='semantic_vector_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='audioclip',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['acoustic_vector'], m=16, name='acoustic_vector_index', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='audioclip',
            constraint=models.CheckConstraint(condition=models.Q(('likes__gte', 0)), name='likes_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audioclip',
            constraint=models.CheckConstraint(condition=models.Q(('shares__gte', 0)), name='shares_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audioclip',
            constraint=models.CheckConstraint(condition=models.Q(('skips__gte', 0)), name='skips_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audioclip',
            constraint=models.CheckConstraint(condition=models.Q(('comment_count__gte', 0)), name='comment_count_non_negative'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='app_auditlo_user_id_ed87c0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['correlation_id'], name='app_auditlo_correla_48af7e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['clip', '-created_at'], name='app_comment_clip_id_84fef2_idx'),
        ),
        migrations.AddIndex(
            model_name='consentaudit',
            index=models.Index(fields=['user', '-consent_issued_at'], name='app_consent_user_id_f45390_idx'),
        ),
        migrations.AddIndex(
            model_name='datasubjectrequest',
            index=models.Index(fields=['user', 'request_type'], name='app_datasub_user_id_e1167a_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['user', '-created_at'], name='app_grievan_user_id_435781_idx'),
        ),
        migrations.AddIndex(
            model_name='shareevent',
            index=models.Index(fields=['receiver', '-created_at', 'is_read'], name='app_shareev_receive_865473_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='app_userint_user_id_afb673_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'clip', 'interaction_type')},
        ),
    ]
